### ISSUE TITLE
Unable to use network in separate project as "authorized_network"

### ISSUE THREAD

**Issue by chaopeng** [terraform-google-modules/terraform-google-memorystore#29]
Input:

We have 2 project in this case:

- network project: located a centralized network
- app project: host GKE and memorystore(redis)

```
module "memorystore" {
  source  = "terraform-google-modules/memorystore/google"
  version = "1.3.0"

  name               = "xxxxxxx"
  project            = module.project.project_id
  region             = "us-central1"
  authorized_network = "projects/[network-project-id]/us-central1/networks/[network-id]"
  connect_mode       = "PRIVATE_SERVICE_ACCESS"
  memory_size_gb     = 1
}
```

Error message:

```
Error: Error creating Instance: googleapi: Error 400: Network name is not valid. Specify a valid name and try again.
com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: Network name is not valid. Specify a valid name and try again.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Invalid value: projects/[apps-project-id]/global/networks/[network-id]",
        "field": "instance.authorized_network"
      }
    ]
  }
]
```

Is seems like a expected behavior, is it possible to fix or any workaround?

**Comment by xingao267** [comment]
@morgante @bharathkkb  could you help take a look? It looks like a bug in the `google_redis_instance` resource.

**Comment by bharathkkb** [comment]
@xingao267 I don't see anything being done in the provider other than [just passing it as is](https://github.com/hashicorp/terraform-provider-google/blob/31001bd420a947a2c56882df51f88671b283ff7f/google/resource_redis_instance.go#L216). I will try to repro this

**Comment by xingao267** [comment]
The issues seems, when you want to specify a network in a separate project, the `google_redis_instance` resource would remove the `projects/[network-project-id]/us-central1/networks/` project and left with just the network name, and then the resource will try to use the network with `[network-id]` in the service project.

**Comment by bharathkkb** [comment]
@xingao267 I think there is an issue with the URI for networks. Networks are a global resource, IIRC it should be something like `projects/[network-project]/global/networks/[network-name]`

**Comment by xingao267** [comment]
@chaopeng could you try with the global path?

**Comment by chaopeng** [comment]
The global path works for me. Also https://github.com/terraform-google-modules/terraform-google-memorystore/issues/30 is useful for Shared VPC setup. Thank you folks.
