### ISSUE TITLE
Warning of Interpolation-only expressions are deprecated

### ISSUE THREAD

**Issue by indrajitp** [terraform-google-modules/terraform-google-memorystore#34]
Hi There,

I am using this memorystore module in my code with version **1.3.0**, I am still getting below warning -

> Warning: Interpolation-only expressions are deprecated
> on .terraform\modules\memorystore\main.tf line 44, in module "enable_apis":
> 44:   project_id  = "${var.project}"

Provider version is - 3.48.0. 

Here is my code -
`
module "memorystore" {

  count   = length(var.tesla_vpc_subnetworks) 
  source  = "terraform-google-modules/memorystore/google"
  version = "1.3.0"
  name    = "${lookup(var.tesla_vpc_subnetwork_regions, element(var.tesla_vpc_subnetworks, count.index))}-cache"
  project = var.project_id
  authorized_network = google_compute_network.tesla_vpc.name
  memory_size_gb = lookup(var.memory_store_size, var.environment)
  labels = var.labels
  redis_version = var.redis_version
  region = lookup(var.tesla_vpc_subnetwork_regions, element(var.tesla_vpc_subnetworks, count.index))
  tier = lookup(var.memory_store_tier, var.environment)
  redis_configs = var.redis_config
  enable_apis = true
}
`

**Comment by bharathkkb** [comment]
@indrajitp Thanks for the report. Just released `1.3.1` which should have the fix.
