### ISSUE TITLE
Not able to create redis instance using open source modules

### ISSUE THREAD

**Issue by dhinakar-falabella** [terraform-google-modules/terraform-google-memorystore#41]
Hi Team,

When i tried creating redis instance using open-source TF module, getting error while passing redis_reserved_ip_range.

source module: "git::https://github.com/terraform-google-modules/terraform-google-memorystore.git/?ref=release-v1.3.1"

![image](https://user-images.githubusercontent.com/69041163/107194012-87322500-6a15-11eb-8a70-0ea2be24fd32.png)

Please can anyone check and help me to fix this issue, Also I'm using TF version 0.14.4

**Comment by morgante** [comment]
This looks like a bug we need to fix.

**Comment by dhinakar-falabella** [comment]
Please can we change the below default value to string from null, it should work fine.

==============
variable "reserved_ip_range" {
  description = "The CIDR range of internal addresses that are reserved for this instance."
  type        = string
  default     = null
}

**Comment by dhinakar-falabella** [comment]
@morgante Shall i change the code and share the MR to fix this?

**Comment by morgante** [comment]
Sure, I'm happy to review a PR.

**Comment by dhinakar-falabella** [comment]
sure, I will check and update you my PR here by tomorrow.

@morgante I have one issue with below module also, shall i share the PR for same. Will you be able to review and help me out.
https://github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql"

**Comment by morgante** [comment]
Yes I can review a PR there too.

**Comment by dhinakar2707** [comment]
@morgante I have done with my code changes, but not able to push my code and create new PR.

getting below error, please can you help me how to fix it.

fatal: Authentication failed for 'https://github.com/terraform-google-modules/terraform-google-memorystore.git/

**Comment by morgante** [comment]
@dhinakar2707 You need to fork and make a pull request from there - https://guides.github.com/activities/forking/

**Comment by dhinakar2707** [comment]
@morgante please can you review below PR which resolved couple of issues with users who is using terraform version >=0.13 & it allows to set redis reserved IP range.

=================
https://github.com/terraform-google-modules/terraform-google-memorystore/pull/43

**Comment by dhinakar2707** [comment]
@morgante If the code looks good and if we are able to merge it, please send me the release tag, so that i can use in my dev project and try to create new redis instances.

**Comment by dhinakar2707** [comment]
@morgante Do we have any update on this, did you get some time to review my PR?

**Comment by morgante** [comment]
@dhinakar2707 Have you tested your change?

Having a default shouldn't make any difference so I'm worried your fix isn't correct.

**Comment by dhinakar2707** [comment]
@morgante Sorry for the delay...I was on vacation. Again I will validate the same code in my local and will share you the updates. Please give me some more time...

**Comment by dhinakar2707** [comment]
@morgante 

We are using terraform open-source terraform module for creating postgres sql instance...where we are using same code for creating postgres sql instance in multiple environments like dev, staging & production.
Where we require read replica instance only for production, it's not needed for dev & staging. With the current master code we are not able to restrict this approach, so I have added a count condition with a boolean flag. Please have a review on this PR and let me know if this make sense. Also let me know if i have missed something from my end.
can we add a conditional flag like below for the read_replica resources, which will be the good solution too.

==========
count = var.read_replica_enable == true ? 1 : 0
Also i ha
