### ISSUE TITLE
Unable create redis instance using open source module: invalid arg for Network name

### ISSUE THREAD

**Issue by sukhjit-chomber-db** [terraform-google-modules/terraform-google-memorystore#59]
Hi,

When using https://registry.terraform.io/modules/terraform-google-modules/memorystore/google/latest (version = "3.1.0")

I get the following around the `authorised_network` attribute
 
My GCP project makes use of a VPC hosted by another project.
 
We are able to build out a GKE cluster using the same VPC.
My code has the settings
 
`authorized_network = "shared-vpc-dev-01"

 connect_mode = "PRIVATE_SERVICE_ACCESS"

 redis_version = "REDIS_5_0"`

But TF apply always fails (the network is being expanded to full name):

![image](https://user-images.githubusercontent.com/82879032/123381342-87782a80-d588-11eb-8f0e-79f682fa99e7.png)

**Comment by morgante** [comment]
Is this not the correct network name?

**Comment by sukhjit-chomber-db** [comment]
Network reference should be that of the host project and not the service project.

Attributes corrected and instance is now built.

Closing issue.
