### ISSUE TITLE
Error in docs `transit_encryption_mode`

### ISSUE THREAD

**Issue by jacek-jablonski** [terraform-google-modules/terraform-google-memorystore#63]
Hi,
The docs about `transit_encryption_mode` says: `"The TLS mode of the Redis instance, If not provided, TLS is disabled for the instance."`.
It seems this is not true. By default, an instance with TLS enabled is created. TLS enablement is specified here: https://github.com/terraform-google-modules/terraform-google-memorystore/blob/master/variables.tf#L114.

Thanks.

**Comment by morgante** [comment]
It's somewhat poorly phrased. If the value is explicitly set to null, TLS will be disabled. Agreed we should fix this—happy to review a PR.
